### PR TITLE
update Tooltip docs

### PR DESCRIPTION
**Pull request by richbai90**
I've been having a lengthy discussion with the definitely typed team about adding these attributes. They understandably are hesitant to add undocumented types.  Since the underlying code base makes use of these types, and they are useful when creating a custom tooltip, they should be documented.

See the PR on definitely typed [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23057#issuecomment-360216490)
I also opened an issue on the recharts main repo [here](https://github.com/recharts/recharts/issues/1149)

### CODE REVIEW

**Comment by naw** [comment]
What's confusing to me is that the docs mix together two things:

1. The props you give to `<Tooltip />` yourself within a chart "definition" in order to configure the tooltip.
2. The props that recharts gives to the underlying content renderer for the tooltip, whether it be the default one or a custom one.  

Granted, there is a lot of overlap between these, but not entirely, because recharts calculates a lot of stuff for you and you can't actually configure it from the chart itself (`color`, for example).

I think this PR is good in the sense that it adds some of the attributes that recharts gives to the custom tooltip component within the `payload` prop, but even with this PR, overall it's still difficult to know what props a custom tooltip actually gets without actually diving into the source code.

**Comment by naw** [comment]
In other words, the docs are not distinguishing between props you _give_ to recharts vs. props you _get from_ recharts.

**Comment by richbai90** [comment]
You make a good point. If there is any guidance on how these items are calculated and when they can be expected to be available I'd happily write it up in more detail. My knowledge thus far has come from examining the code at length until I could figure out what was going on. That is certainly error prone at best.

**Comment by xile611** [comment]
Thanks for all your suggestion! In my opinion,  show all the `underlying props` of `Tooltip` is confused Which may be not stable. So I don't list these props!

**Pull request closed without merging**
